FROM python:3.12-slim-buster

WORKDIR /app

# Instala tzdata para configurar o fuso horário
RUN apt-get update && apt-get install -y tzdata git && \
    ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && echo America/Sao_Paulo > /etc/timezone && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY websocket_server/requirements.txt . # Assumindo que o websocket_server tem seu próprio requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY websocket_server.py /app/websocket_server.py # Copia o arquivo do servidor WebSocket
COPY robo_trader/state_manager.py /app/robo_trader/state_manager.py # Se o websocket_server precisa do state_manager
# Copie outros arquivos que o websocket_server precise e que estejam na raiz do projeto
