FROM python:3.12-slim-buster

WORKDIR /app

# Instala tzdata para configurar o fuso horário
RUN apt-get update && apt-get install -y tzdata git && \
    ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && echo America/Sao_Paulo > /etc/timezone && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY robo_cliente/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY robo_cliente /app/robo_cliente
COPY client.py /app/client.py # Se client.py for compartilhado ou estiver na raiz
COPY config.py /app/config.py # Se config.py for compartilhado ou estiver na raiz
# Copie outros arquivos que o robo_cliente precise e que estejam na raiz do projeto
