# robo_trader/Dockerfile.robo-trader
FROM python:3.12-slim-buster

WORKDIR /app

# Instala tzdata para configurar o fuso horário e garantir logs corretos
RUN apt-get update && apt-get install -y tzdata \
    && rm -rf /var/lib/apt/lists/*

# Define o fuso horário para evitar avisos e garantir consistência de logs
ENV TZ=America/Sao_Paulo
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# --- INSTALAÇÃO DAS DEPENDÊNCIAS PYTHON ---
# Copia o arquivo de requisitos para o cache do Docker
COPY robo_trader/requirements.txt .
# Instala as dependências Python listadas no requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia o arquivo tar.gz do pandas-ta para o WORKDIR
COPY robo_trader/pandas_ta-0.4.71b0.tar.gz .
# Instala o pandas-ta a partir do arquivo local
RUN pip install --no-cache-dir ./pandas_ta-0.4.71b0.tar.gz
# --- FIM DA INSTALAÇÃO DAS DEPENDÊNCIAS ---

# Copia todos os arquivos do robo_trader para o WORKDIR /app
# Isso deve ser feito DEPOIS de instalar todas as dependências
COPY robo_trader/ .

# Comando para iniciar o servidor WebSocket e o robô trader
# Usaremos um script de entrada para iniciar ambos em segundo plano
COPY robo_trader/start_robo_trader.sh .
RUN chmod +x start_robo_trader.sh

CMD ["./start_robo_trader.sh"]
